version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: forexbot_postgres
    environment:
      POSTGRES_DB: forexbot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    networks:
      - forexbot_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: forexbot_backend
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=forexbot
      - PORT=3000
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_SECRET=${BINANCE_SECRET}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - forexbot_network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: forexbot_frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - forexbot_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  forexbot_network:
    driver: bridge
